# Generated by Django 3.2 on 2021-10-03 07:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='author', editable=False, max_length=6)),
                ('host', models.URLField(editable=False, max_length=32)),
                ('url', models.URLField(editable=False, max_length=128)),
                ('displayName', models.CharField(max_length=32)),
                ('github', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='post', editable=False, max_length=4)),
                ('contentType', models.TextField(default='text/plain', editable=False)),
                ('content', models.TextField(default='lorem ipsum dolor sit amet')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newconnectionwhodis.author')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newconnectionwhodis.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newconnectionwhodis.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='comment', editable=False, max_length=7)),
                ('published', models.DateTimeField(default='2021-10-03T07:57:21.746389+00:00', editable=False)),
                ('contentType', models.TextField(default='text/markdown', editable=False)),
                ('comment', models.CharField(max_length=280)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newconnectionwhodis.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newconnectionwhodis.post')),
            ],
        ),
    ]
