# Generated by Django 3.2.7 on 2021-10-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newconnectionwhodis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default='26b2838821c947ec83dfb73e204d2913', editable=False, primary_key=True, serialize=False),
        ),
    ]
